import 'dart:convert';
import 'dart:ui';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:my_nihongo/features/content/models/content_catalog.dart';
import 'package:my_nihongo/features/content/models/jlpt_level.dart';
import 'package:my_nihongo/features/content/models/localized_strings.dart';
import 'package:my_nihongo/features/content/models/parts_of_speech.dart';
import 'package:my_nihongo/features/content/models/vocab_entry.dart';
import 'package:my_nihongo/features/content/services/content_repository.dart';
import 'package:my_nihongo/features/kana/models/kana.dart';
import 'package:my_nihongo/features/progress/models/study_record.dart';

/// Purpose: Check the bundled content parses and meets the catalog rules.
/// Inputs: None.
/// Returns: None.
/// Side effects: Reads the content assets.
/// Notes: The catalog is generated by `tool/import_vocab.dart` from JMdict and
/// the JLPT lists, so these cases are the gate on that tool as much as on the
/// files: ids unique across every kind, the 24 hand-written seed ids still
/// resolving through their aliases, plausible counts per level, and no entry
/// without a meaning. Chinese is required on the levels that have been
/// translated and on the seed words, not on the whole catalog — see
/// `doc/en-us/features/content-catalog.md`.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late ContentCatalog catalog;

  /// The ids the hand-written seed shipped under, before the JMdict import.
  /// A shipped id is never retired, so each has to keep resolving.
  const seedIds = [
    'vocab:watashi',
    'vocab:gakusei',
    'vocab:sensei',
    'vocab:hon',
    'vocab:mizu',
    'vocab:taberu',
    'vocab:nomu',
    'vocab:iku',
    'vocab:kuru',
    'vocab:miru',
    'vocab:kau',
    'vocab:ookii',
    'vocab:chiisai',
    'vocab:atarashii',
    'vocab:genki',
    'vocab:suki',
    'vocab:kyou',
    'vocab:ashita',
    'vocab:jikan',
    'vocab:gakkou',
    'vocab:tomodachi',
    'vocab:nihongo',
    'vocab:arigatou',
    'vocab:sumimasen',
  ];

  setUpAll(() async {
    ContentRepository.parseInIsolate = false;
    catalog = await ContentRepository.load();
  });

  tearDownAll(() => ContentRepository.parseInIsolate = true);

  test('the generated content loads and is the expected size', () {
    expect(catalog.vocab.length, greaterThan(5000));
    expect(catalog.vocab.length, lessThan(12000));
    expect(catalog.grammar.length, greaterThanOrEqualTo(80));
    expect(catalog.kanaNotes, isNotEmpty);
  });

  test('each level carries a plausible number of words', () {
    final counts = <JlptLevel, int>{};
    for (final entry in catalog.vocab) {
      counts[entry.level] = (counts[entry.level] ?? 0) + 1;
    }
    expect(counts[JlptLevel.n5], greaterThanOrEqualTo(500));
    expect(counts[JlptLevel.n4], greaterThanOrEqualTo(500));
    expect(counts[JlptLevel.n3], greaterThanOrEqualTo(1000));
    expect(counts[JlptLevel.n2], greaterThanOrEqualTo(1000));
    expect(counts[JlptLevel.n1], greaterThanOrEqualTo(2000));
  });

  test('every id is unique and carries its kind prefix', () {
    final ids = <String>{};
    for (final id in catalog.allVocabIds) {
      expect(ids.add(id), isTrue, reason: 'duplicate $id');
      expect(studyKindOf(id), StudyKind.vocab, reason: id);
    }
    for (final point in catalog.grammar) {
      expect(ids.add(point.id), isTrue, reason: 'duplicate ${point.id}');
      expect(studyKindOf(point.id), StudyKind.grammar, reason: point.id);
    }
    for (final kana in allKanaEntries()) {
      expect(ids.add(kana.progressId), isTrue, reason: kana.progressId);
      expect(studyKindOf(kana.progressId), StudyKind.kana);
    }
  });

  test('no alias collides with a primary id', () {
    final primaries = {for (final entry in catalog.vocab) entry.id};
    for (final entry in catalog.vocab) {
      for (final alias in entry.aliases) {
        expect(
          primaries.contains(alias),
          isFalse,
          reason: '$alias is both an alias and a primary id',
        );
      }
    }
  });

  test('every seed id still resolves through its alias', () {
    for (final id in seedIds) {
      final entry = catalog.vocabById(id);
      expect(entry, isNotNull, reason: 'retired id $id no longer resolves');
      expect(entry!.id, startsWith('vocab:jm'), reason: id);
      expect(entry.aliases, contains(id), reason: id);
      expect(catalog.canonicalId(id), entry.id);
    }
  });

  test('no level repeats a headword and reading', () {
    final seen = <String>{};
    for (final entry in catalog.vocab) {
      final key = '${entry.level.name}|${entry.headword}|${entry.reading}';
      expect(seen.add(key), isTrue, reason: 'duplicate $key');
    }
  });

  test('every part-of-speech tag is one the app knows', () {
    for (final entry in catalog.vocab) {
      for (final pos in entry.partsOfSpeech) {
        expect(
          vocabPartsOfSpeech,
          contains(pos),
          reason: '${entry.id} carries unknown tag $pos',
        );
      }
    }
  });

  test('every vocabulary entry has an English meaning', () {
    const en = Locale('en');
    for (final entry in catalog.vocab) {
      expect(entry.meanings.resolve(en), isNotEmpty, reason: entry.id);
    }
  });

  test('N5 and every seed word also have Chinese', () {
    const zh = Locale('zh');
    for (final entry in catalog.vocab) {
      final needsChinese =
          entry.level == JlptLevel.n5 || entry.aliases.isNotEmpty;
      if (!needsChinese) continue;
      expect(
        entry.meanings.values.keys,
        contains('zh'),
        reason: '${entry.id} (${entry.headword}) has no Chinese gloss',
      );
      expect(entry.meanings.resolve(zh), isNotEmpty, reason: entry.id);
    }
  });

  test('the overlay matches what the catalog ships', () async {
    // Catches a forgotten `--overlay-only` run: the overlay is the source of
    // truth for Chinese, and an edit that never reached the catalog would
    // otherwise pass unnoticed.
    final raw = await rootBundle.loadString('assets/content/vocab_zh.json');
    final overlay = (jsonDecode(raw) as Map<String, dynamic>)['entries'] as Map;
    expect(overlay, isNotEmpty);
    for (final row in overlay.entries) {
      final id = row.key.toString();
      final entry = catalog.vocabById(id);
      expect(entry, isNotNull, reason: 'overlay id $id is not in the catalog');
      final zh = (row.value as Map)['zh'];
      if (zh is! List || zh.isEmpty) continue;
      // A seed gloss deliberately wins over the overlay, so only check the
      // entries the overlay actually owns.
      if (entry!.aliases.isNotEmpty) continue;
      expect(
        entry.meanings.values['zh'],
        zh,
        reason: 'overlay and catalog disagree on $id',
      );
    }
  });

  test('every grammar point has both languages and examples', () {
    const en = Locale('en');
    const zh = Locale('zh');
    for (final point in catalog.grammar) {
      expect(point.meaning.values.keys, containsAll(['en', 'zh']));
      expect(point.explanation.values.keys, containsAll(['en', 'zh']));
      expect(point.examples, isNotEmpty, reason: point.id);
      for (final example in point.examples) {
        expect(example.ja, isNotEmpty, reason: point.id);
        expect(example.translations.resolve(en), isNotEmpty, reason: point.id);
        expect(example.translations.resolve(zh), isNotEmpty, reason: point.id);
      }
    }
  });

  test('every kana note names a kana that exists, in both languages', () {
    const en = Locale('en');
    const zh = Locale('zh');
    for (final note in catalog.kanaNotes.entries) {
      expect(
        kanaEntryById(note.key),
        isNotNull,
        reason: '${note.key} is not in the kana tables',
      );
      expect(note.value.hint.resolve(en), isNotEmpty, reason: note.key);
      expect(note.value.hint.resolve(zh), isNotEmpty, reason: note.key);
      for (final other in note.value.confusableWith) {
        expect(kanaEntryById(other), isNotNull, reason: other);
      }
    }
  });

  test('lookups and search behave', () {
    final watashi = catalog.vocabById('vocab:watashi');
    expect(watashi, isNotNull);
    expect(watashi!.level, JlptLevel.n5);
    expect(watashi.hasKanji, isTrue);
    expect(watashi.matches('私'), isTrue);
    expect(watashi.matches('わたし'), isTrue);
    expect(watashi.matches('watashi'), isTrue);
    expect(watashi.matches('我'), isTrue);
    expect(watashi.matches('zzz'), isFalse);

    final arigatou = catalog.vocabById('vocab:arigatou');
    expect(arigatou!.hasKanji, isFalse);

    final desu = catalog.grammarById('grammar:desu');
    expect(desu, isNotNull);
    expect(desu!.matches('です'), isTrue);
    expect(desu.matches('copula'), isTrue);
    expect(desu.matchForms, isNotEmpty);
  });

  test('an unknown id resolves to itself', () {
    expect(catalog.vocabById('vocab:nope'), isNull);
    expect(catalog.canonicalId('vocab:nope'), 'vocab:nope');
  });

  test('localized strings fall back to English, then anything', () {
    const strings = LocalizedStrings({
      'en': ['one'],
      'ja': ['いち'],
    });
    expect(strings.resolve(const Locale('zh')), ['one']);
    expect(strings.resolve(const Locale('ja')), ['いち']);
    const noEnglish = LocalizedStrings({
      'ja': ['いち'],
    });
    expect(noEnglish.resolve(const Locale('zh')), ['いち']);
    expect(LocalizedStrings.empty.resolve(const Locale('en')), isEmpty);
    expect(LocalizedStrings.fromJson('bare').resolve(const Locale('zh')), [
      'bare',
    ]);
  });

  test('malformed entries are skipped rather than fatal', () {
    expect(VocabEntry.fromJson({'id': 'vocab:x'}), isNull);
    expect(
      VocabEntry.fromJson({'id': 'vocab:x', 'level': 'N9', 'reading': 'x'}),
      isNull,
    );
    final parsed = ContentCatalog.fromJson({
      'entries': [
        1,
        {'id': 'vocab:ok', 'level': 'n5', 'reading': 'おけ'},
      ],
    }, const []);
    expect(parsed.vocab.single.id, 'vocab:ok');
    expect(parsed.vocab.single.headword, 'おけ');
    expect(parsed.grammar, isEmpty);
    expect(parsed.kanaNotes, isEmpty);
  });

  test('JLPT levels parse case-insensitively and label themselves', () {
    expect(JlptLevel.parse('N1'), JlptLevel.n1);
    expect(JlptLevel.parse('n3'), JlptLevel.n3);
    expect(JlptLevel.parse('N6'), isNull);
    expect(JlptLevel.parse(5), isNull);
    expect(JlptLevel.n5.label, 'N5');
  });
}
