/// Purpose: Model the sentence-lab and writing-practice history that rides in
/// the progress file, so a sentence analysed on one device can be reopened on
/// another.
/// Inputs: `lab:` and `writing:` records inside `nihongo_progress.json`.
/// Returns: The [HistoryEntry] model and the helpers that read and write it.
/// Side effects: None; persistence is `NihongoStorage`'s job.
/// Notes: Only the **input** is stored — the sentence, the unit it belongs to
/// and when it was last opened. The analysis is recomputed on open, because it
/// is a pure function of the text and the shipped catalog, and storing it would
/// freeze an answer the next release improves. Nothing generated by a model is
/// ever stored here; that is a behavior contract in `AGENTS.md`.
library;

import 'study_record.dart';

/// Which page an entry came from.
enum HistoryKind {
  /// The sentence lab.
  lab('lab'),

  /// Writing practice.
  writing('writing');

  const HistoryKind(this.prefix);

  /// The record-id prefix, which is also what [studyKindOf] matches on.
  final String prefix;
}

/// How many entries of one kind are kept.
///
/// A cap rather than unlimited growth: the progress file is downloaded, merged
/// and uploaded whole on every sync, and an unbounded log of everything ever
/// typed would eventually dominate a file whose real content is a few thousand
/// small records.
const historyMaxEntries = 100;

/// The `extraJson` key the payload lives under.
const _historyPayloadKey = 'history';

/// One remembered sentence or piece of writing.
class HistoryEntry {
  /// Purpose: Describe one history entry.
  /// Inputs: `id`, `kind`, the `text` that was analysed, the `unitId` it came
  /// from when it did, and `at` — when it was last opened.
  /// Returns: A new `HistoryEntry` instance.
  /// Side effects: None.
  /// Notes: `at` is the record's `modifiedAt`, so re-opening an entry moves it
  /// to the top without a second timestamp to keep in step.
  const HistoryEntry({
    required this.id,
    required this.kind,
    required this.text,
    required this.at,
    this.unitId,
  });

  /// The record id, `lab:<hash>` or `writing:<hash>`.
  final String id;

  /// Which page this came from.
  final HistoryKind kind;

  /// What the learner typed, as it was analysed.
  final String text;

  /// The lesson unit a writing exercise belongs to, when it had one.
  final String? unitId;

  /// When the entry was last written, UTC.
  final DateTime at;

  /// Purpose: Build the content-addressed id for one entry.
  /// Inputs: `kind`, the `text`, and the `unitId` when there is one.
  /// Returns: `String` — `<prefix>:<16 hex digits>`.
  /// Side effects: None.
  /// Notes: Keyed by content rather than by a random id, so analysing the same
  /// sentence twice updates one record and moves it to the top instead of
  /// filling the history with duplicates. That also makes the id stable across
  /// devices: two phones that analysed the same sentence merge into one entry
  /// rather than conflicting. The text is trimmed and its internal whitespace
  /// collapsed first, so a stray space does not make a second entry.
  static String buildId(
    HistoryKind kind,
    String text, {
    String? unitId,
  }) {
    final key = '${unitId ?? ''}\n${normalizeText(text)}';
    return '${kind.prefix}:${_fnv1a64Hex(key)}';
  }

  /// Purpose: Normalize the text an id is derived from and the entry stores.
  /// Inputs: `text`.
  /// Returns: `String`.
  /// Side effects: None.
  /// Notes: Trimmed, with runs of whitespace collapsed to one space. Newlines
  /// count as whitespace: writing practice is several sentences in one field,
  /// and where the learner pressed return is not what makes it a different
  /// piece of writing.
  static String normalizeText(String text) =>
      text.trim().replaceAll(RegExp(r'\s+'), ' ');

  /// Purpose: Read an entry out of a progress record.
  /// Inputs: `record`.
  /// Returns: `HistoryEntry?` — null when the record is not a history record
  /// or its payload cannot be read.
  /// Side effects: None.
  /// Notes: Never throws. A payload written by a newer build with fields this
  /// one cannot read still loads, because every field is read independently.
  /// An entry with no text is refused rather than shown as a blank row.
  static HistoryEntry? fromRecord(StudyRecord? record) {
    if (record == null) return null;
    final kind = kindOf(record.id);
    if (kind == null) return null;
    final raw = record.extraJson[_historyPayloadKey];
    if (raw is! Map) return null;
    final text = raw['text'];
    if (text is! String || text.trim().isEmpty) return null;
    final unitId = raw['unitId'];
    return HistoryEntry(
      id: record.id,
      kind: kind,
      text: text,
      unitId: unitId is String && unitId.isNotEmpty ? unitId : null,
      at: record.modifiedAt,
    );
  }

  /// Purpose: Report which page a record id belongs to.
  /// Inputs: `id`.
  /// Returns: `HistoryKind?` — null for every other kind of record.
  /// Side effects: None.
  /// Notes: None.
  static HistoryKind? kindOf(String id) {
    final sep = id.indexOf(':');
    if (sep < 0) return null;
    final prefix = id.substring(0, sep);
    for (final kind in HistoryKind.values) {
      if (kind.prefix == prefix) return kind;
    }
    return null;
  }

  /// Purpose: Write the entry back into its record.
  /// Inputs: `existing` — the record already in the file, if any; `now`.
  /// Returns: `StudyRecord` ready for `upsertRecords`.
  /// Side effects: None.
  /// Notes: Unknown keys inside the payload are preserved, the same rule the
  /// learner profile follows: an older build must not drop a newer one's
  /// fields on the first edit. The counters stay at zero — a remembered
  /// sentence is not something anybody answered.
  StudyRecord toRecord(StudyRecord? existing, DateTime now) {
    final previous = existing?.extraJson[_historyPayloadKey];
    final payload = <String, dynamic>{
      if (previous is Map)
        for (final entry in previous.entries) entry.key.toString(): entry.value,
      'text': text,
      if (unitId != null) 'unitId': unitId,
    };
    final extra = <String, dynamic>{
      ...?existing?.extraJson,
      _historyPayloadKey: payload,
    };
    final base = existing ?? StudyRecord.create(id, now: now);
    return base.copyWith(extraJson: extra, modifiedAt: now.toUtc());
  }

  /// Purpose: Create an entry for text the learner just submitted.
  /// Inputs: `kind`, `text`, `unitId`, and `now` for tests.
  /// Returns: `HistoryEntry?` — null when the text is blank.
  /// Side effects: None.
  /// Notes: The stored text is the normalized one, so what is replayed on open
  /// is what the id was derived from.
  static HistoryEntry? forInput(
    HistoryKind kind,
    String text, {
    String? unitId,
    DateTime? now,
  }) {
    final normalized = normalizeText(text);
    if (normalized.isEmpty) return null;
    return HistoryEntry(
      id: buildId(kind, normalized, unitId: unitId),
      kind: kind,
      text: normalized,
      unitId: unitId,
      at: (now ?? DateTime.now()).toUtc(),
    );
  }
}

/// Purpose: Collect one kind of history out of the progress file, newest first.
/// Inputs: `records`, the `kind` wanted, and `unitId` to narrow a writing
/// history to one unit.
/// Returns: `List<HistoryEntry>`.
/// Side effects: None.
/// Notes: Sorted by `modifiedAt` descending, with the id as a tie-break so the
/// order is total and two entries written in the same millisecond cannot swap
/// places between builds. A `unitId` of null means every unit.
List<HistoryEntry> historyEntries(
  Iterable<StudyRecord> records, {
  required HistoryKind kind,
  String? unitId,
}) {
  final entries = <HistoryEntry>[];
  for (final record in records) {
    final entry = HistoryEntry.fromRecord(record);
    if (entry == null || entry.kind != kind) continue;
    if (unitId != null && entry.unitId != unitId) continue;
    entries.add(entry);
  }
  entries.sort((a, b) {
    final byTime = b.at.compareTo(a.at);
    return byTime != 0 ? byTime : a.id.compareTo(b.id);
  });
  return entries;
}

/// Purpose: Hash a string to 16 hex digits.
/// Inputs: `input`.
/// Returns: `String`.
/// Side effects: None.
/// Notes: Two independent FNV-1a 32-bit lanes, differing only in their offset
/// basis, concatenated. A dependency was not worth adding for a de-duplication
/// key: this decides whether two sentences are the same sentence, and a
/// collision costs one history entry shadowing another. The prime is applied in
/// shift-add form so no intermediate exceeds 32 bits, which keeps the result
/// identical on every platform rather than depending on the width of an `int`.
String _fnv1a64Hex(String input) {
  final a = _fnv1a32(input, 0x811c9dc5);
  final b = _fnv1a32(input, 0x01000193);
  return a.toRadixString(16).padLeft(8, '0') +
      b.toRadixString(16).padLeft(8, '0');
}

/// Purpose: Run one FNV-1a 32-bit lane over a string's code units.
/// Inputs: `input`, the `seed` offset basis.
/// Returns: `int` in the 32-bit range.
/// Side effects: None.
/// Notes: Internal helper used within this file only. `hash * 16777619` is
/// written as `(hash << 24) + (hash << 8) + hash * 0x93`, each term masked, so
/// the multiplication never needs more than 32 bits of precision.
int _fnv1a32(String input, int seed) {
  var hash = seed;
  for (final unit in input.codeUnits) {
    hash ^= unit & 0xff;
    hash = _fnvPrime(hash);
    hash ^= (unit >> 8) & 0xff;
    hash = _fnvPrime(hash);
  }
  return hash & 0xffffffff;
}

/// Purpose: Multiply by the FNV-1a 32-bit prime without overflowing 32 bits.
/// Inputs: `hash`.
/// Returns: `int` in the 32-bit range.
/// Side effects: None.
/// Notes: Internal helper used within this file only.
int _fnvPrime(int hash) {
  final shifted =
      (hash << 24) + (hash << 8) + (hash * 0x93);
  return shifted & 0xffffffff;
}
